{"uuid": "45ef5e54-2476-4d10-b013-03d795bc28d8", "children": ["a72d209e-cd31-4d5a-b978-05296c4c531d"], "befores": [{"name": "login_to_setting", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff699e16f65+78965]\n\tGetHandleVerifier [0x0x7ff699e16fc0+79056]\n\t(No symbol) [0x0x7ff699ba9dda]\n\t(No symbol) [0x0x7ff699b965d0]\n\t(No symbol) [0x0x7ff699b94ce9]\n\t(No symbol) [0x0x7ff699b9559f]\n\t(No symbol) [0x0x7ff699bc0cab]\n\t(No symbol) [0x0x7ff699bb42c0]\n\t(No symbol) [0x0x7ff699bb4162]\n\t(No symbol) [0x0x7ff699b85d68]\n\t(No symbol) [0x0x7ff699b83d03]\n\t(No symbol) [0x0x7ff699c69011]\n\t(No symbol) [0x0x7ff699c2866a]\n\t(No symbol) [0x0x7ff699c50dbe]\n\t(No symbol) [0x0x7ff699c28443]\n\t(No symbol) [0x0x7ff699bf1311]\n\t(No symbol) [0x0x7ff699bf20a3]\n\tGetHandleVerifier [0x0x7ff69a0ce26d+2926461]\n\tGetHandleVerifier [0x0x7ff69a0c8993+2903715]\n\tGetHandleVerifier [0x0x7ff69a0e6aed+3026941]\n\tGetHandleVerifier [0x0x7ff699e316fe+187406]\n\tGetHandleVerifier [0x0x7ff699e396ef+220159]\n\tGetHandleVerifier [0x0x7ff699e1faf4+114692]\n\tGetHandleVerifier [0x0x7ff699e1fca9+115129]\n\tGetHandleVerifier [0x0x7ff699e064d8+10728]\n\tBaseThreadInitThunk [0x0x7ffa099e7374+20]\n\tRtlUserThreadStart [0x0x7ffa0b89cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_item\\test_setting.py\", line 26, in login_to_setting\n    driver = create_driver(driver_path)\n  File \"D:\\PycharmProjects\\APS\\Utils\\driver_manager.py\", line 34, in create_driver\n    driver.maximize_window()  # 最大化浏览器窗口\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1752739362094, "stop": 1752739363743}], "start": 1752739362094, "stop": 1752739363894}