[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //input[@placeholder="请选择计划单元"]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //li[text()="金属（演示）"]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //button[contains(@class, "ivu-btn-primary")]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//span[text()="计划管理"])[1]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//span[text()="计划基础数据"])[1]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//span[text()="物品"])[1]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //div[@class="tabsDivItemCon"]/div[text()=" 测试布局A "]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//i[@class="icon-wrapper el-tooltip font21 line-height-15 m-r-12"])[1]
[32mINFO    [0m root:base_page.py:22 查找元素：xpath = //div[text()="是否默认启动:"]/following-sibling::label/span
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //div[text()="是否默认启动:"]/following-sibling::label/span
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//div[@class="demo-drawer-footer"])[3]/button[2]
[32mINFO    [0m root:driver_manager.py:55 🛑 已从实例池移除并关闭 driver：2530264885296
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //input[@placeholder="请选择计划单元"]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //li[text()="金属（演示）"]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = //button[contains(@class, "ivu-btn-primary")]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//span[text()="计划管理"])[1]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//span[text()="计划基础数据"])[1]
[32mINFO    [0m root:base_page.py:40 点击元素：By = xpath, Value = (//span[text()="物品"])[1]
[32mINFO    [0m root:base_page.py:22 查找元素：xpath = //div[@class="tabsDivItemCon"]/div[text()=" 测试布局A "]
[32mINFO    [0m root:base_page.py:34 查找元素：xpath = //div[@class="ivu-modal-content"]//div[text()=" 对不起,在处理您的请求期间,产生了一个服务器内部错误! "]
[32mINFO    [0m root:driver_manager.py:55 🛑 已从实例池移除并关闭 driver：2530264694256
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024D1F9E2500>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/932dafcd404b155b25b71bc1b6f7eef4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024D1F9E3D00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/932dafcd404b155b25b71bc1b6f7eef4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024D1F9E39A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/932dafcd404b155b25b71bc1b6f7eef4
[32mINFO    [0m root:driver_manager.py:55 🛑 已从实例池移除并关闭 driver：2530264885296