[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //input[@placeholder="请选择计划单元"]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //li[text()="金属（演示）"]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //button[contains(@class, "ivu-btn-primary")]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//span[text()="计划管理"])[1]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//span[text()="计划基础数据"])[1]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//span[text()="物品"])[1]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //div[@class="tabsDivItemCon"]/div[text()=" 测试透视表B "]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//i[@class="icon-wrapper el-tooltip font21 line-height-15 m-r-12"])[1]
[32mINFO    [0m root:base_page.py:26 查找元素：xpath = //div[text()="是否默认启动:"]/following-sibling::label/span
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //div[text()="是否默认启动:"]/following-sibling::label/span
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//div[@class="demo-drawer-footer"])[3]/button[2]
[32mINFO    [0m root:driver_manager.py:55 🛑 已从实例池移除并关闭 driver：3082575966560
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //input[@placeholder="请选择计划单元"]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //li[text()="金属（演示）"]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = //button[contains(@class, "ivu-btn-primary")]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//span[text()="计划管理"])[1]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//span[text()="计划基础数据"])[1]
[32mINFO    [0m root:base_page.py:44 点击元素：By = xpath, Value = (//span[text()="物品"])[1]
[32mINFO    [0m root:base_page.py:26 查找元素：xpath = //div[@class="tabsDivItemCon"]/div[text()=" 测试透视表B "]
[32mINFO    [0m root:base_page.py:38 查找元素：xpath = //div[@class="ivu-modal-content"]//div[text()=" 对不起,在处理您的请求期间,产生了一个服务器内部错误! "]
[32mINFO    [0m root:driver_manager.py:55 🛑 已从实例池移除并关闭 driver：3082575958640
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CDB80F0880>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8d9eab7ffb2a528cae024874960b3408
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CDB80F2EC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8d9eab7ffb2a528cae024874960b3408
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CDB80F06D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8d9eab7ffb2a528cae024874960b3408
[32mINFO    [0m root:driver_manager.py:55 🛑 已从实例池移除并关闭 driver：3082575966560