[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //div[@class="ivu-select-head-flex"]/input
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //li[text()="金属（演示）"]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //button[contains(@class, "ivu-btn-primary")]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="系统管理"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="单元设置"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="事务管理"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //div[@id="pane-air"]//span[text()="新建事务"]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //div[label[text()="事务类型"]]//i
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //span[text()="服务"]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //div[label[text()="配置参数"]]//i[@class="ivu-icon ivu-icon-md-albums paramIcon"]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//div[@class="h-40px flex-justify-end flex-align-items-end b-t-s-d9e3f3"])[2]//span[text()="确定"]
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B0F5F0C1C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c1887269024aca47ebe6c754ee0b6164
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B0F5F0E1A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c1887269024aca47ebe6c754ee0b6164
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B0F5F0E170>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c1887269024aca47ebe6c754ee0b6164
[32mINFO    [0m root:driver_manager.py:56 🛑 已从实例池移除并关闭 driver：2959062042080