{"uuid": "e6d084d4-6a81-4076-aecd-d8f528ea125f", "children": ["32002f28-186e-472c-a655-88a380e7f258"], "befores": [{"name": "login_to_psi", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff76f8b6f65+78965]\n\tGetHandleVerifier [0x0x7ff76f8b6fc0+79056]\n\t(No symbol) [0x0x7ff76f649dda]\n\t(No symbol) [0x0x7ff76f6220d1]\n\t(No symbol) [0x0x7ff76f6cff4e]\n\t(No symbol) [0x0x7ff76f6f06cd]\n\t(No symbol) [0x0x7ff76f6c8443]\n\t(No symbol) [0x0x7ff76f691311]\n\t(No symbol) [0x0x7ff76f6920a3]\n\tGetHandleVerifier [0x0x7ff76fb6e26d+2926461]\n\tGetHandleVerifier [0x0x7ff76fb68993+2903715]\n\tGetHandleVerifier [0x0x7ff76fb86aed+3026941]\n\tGetHandleVerifier [0x0x7ff76f8d16fe+187406]\n\tGetHandleVerifier [0x0x7ff76f8d96ef+220159]\n\tGetHandleVerifier [0x0x7ff76f8bfaf4+114692]\n\tGetHandleVerifier [0x0x7ff76f8bfca9+115129]\n\tGetHandleVerifier [0x0x7ff76f8a64d8+10728]\n\tBaseThreadInitThunk [0x0x7fff6edb7374+20]\n\tRtlUserThreadStart [0x0x7fff6fc1cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_psi.py\", line 49, in login_to_psi\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 32, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 16, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1755659211310, "stop": 1755659213156}], "start": 1755659211310, "stop": 1755659213347}