{"uuid": "1cfed1b7-58d8-4935-8aaf-93a7caa9ca44", "children": ["808d8f98-2259-40a3-b16a-56a01a0fce33"], "befores": [{"name": "login_to_auditlog", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff64c196f65+78965]\n\tGetHandleVerifier [0x0x7ff64c196fc0+79056]\n\t(No symbol) [0x0x7ff64bf29dda]\n\t(No symbol) [0x0x7ff64bf165d0]\n\t(No symbol) [0x0x7ff64bf14ce9]\n\t(No symbol) [0x0x7ff64bf1559f]\n\t(No symbol) [0x0x7ff64bf40cab]\n\t(No symbol) [0x0x7ff64bf342c0]\n\t(No symbol) [0x0x7ff64bf34162]\n\t(No symbol) [0x0x7ff64bf05d68]\n\t(No symbol) [0x0x7ff64bf03d03]\n\t(No symbol) [0x0x7ff64bfe9011]\n\t(No symbol) [0x0x7ff64bfa866a]\n\t(No symbol) [0x0x7ff64bfd0dbe]\n\t(No symbol) [0x0x7ff64bfa8443]\n\t(No symbol) [0x0x7ff64bf71311]\n\t(No symbol) [0x0x7ff64bf720a3]\n\tGetHandleVerifier [0x0x7ff64c44e26d+2926461]\n\tGetHandleVerifier [0x0x7ff64c448993+2903715]\n\tGetHandleVerifier [0x0x7ff64c466aed+3026941]\n\tGetHandleVerifier [0x0x7ff64c1b16fe+187406]\n\tGetHandleVerifier [0x0x7ff64c1b96ef+220159]\n\tGetHandleVerifier [0x0x7ff64c19faf4+114692]\n\tGetHandleVerifier [0x0x7ff64c19fca9+115129]\n\tGetHandleVerifier [0x0x7ff64c1864d8+10728]\n\tBaseThreadInitThunk [0x0x7fffd9ac7374+20]\n\tRtlUserThreadStart [0x0x7fffdad1cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_auditLog.py\", line 31, in login_to_auditlog\n    driver = create_driver(date_driver.driver_path)\n  File \"D:\\PycharmProjects\\APS\\Utils\\driver_manager.py\", line 35, in create_driver\n    driver.maximize_window()  # 最大化浏览器窗口\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1758009979556, "stop": 1758009981218}], "start": 1758009979556, "stop": 1758009981530}