{"uuid": "b1fa8521-89c0-4791-aed1-d9cb7c10f716", "children": ["c537a691-ff83-43c1-84b4-c2a14985c9b0"], "befores": [{"name": "login_to_userrole", "status": "passed", "start": 1757583148741, "stop": 1757583157503}], "afters": [{"name": "login_to_userrole::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_userRole.py\", line 53, in login_to_userrole\n    safe_quit(driver)\n  File \"D:\\PycharmProjects\\APS\\Utils\\driver_manager.py\", line 50, in safe_quit\n    driver.quit()  # 尝试正常关闭浏览器\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 188, in quit\n    super().quit()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 589, in quit\n    self.execute(Command.QUIT)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 427, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 493, in _make_request\n    conn.request(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connection.py\", line 445, in request\n    self.endheaders()\n  File \"D:\\Program Files\\Python310\\lib\\http\\client.py\", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"D:\\Program Files\\Python310\\lib\\http\\client.py\", line 1037, in _send_output\n    self.send(msg)\n  File \"D:\\Program Files\\Python310\\lib\\http\\client.py\", line 975, in send\n    self.connect()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connection.py\", line 276, in connect\n    self.sock = self._new_conn()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connection.py\", line 198, in _new_conn\n    sock = connection.create_connection(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\util\\connection.py\", line 73, in create_connection\n    sock.connect(sa)\n"}, "start": 1757583164867, "stop": 1757583175080}], "start": 1757583148741, "stop": 1757583175080}