{"uuid": "bcf82749-583a-4ddf-b93d-b81ee3ac5830", "children": ["080f435f-114a-4f67-b3de-3591169a3693"], "befores": [{"name": "login_to_environment", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff787026f65+78965]\n\tGetHandleVerifier [0x0x7ff787026fc0+79056]\n\t(No symbol) [0x0x7ff786db9dda]\n\t(No symbol) [0x0x7ff786da65d0]\n\t(No symbol) [0x0x7ff786da4ce9]\n\t(No symbol) [0x0x7ff786da559f]\n\t(No symbol) [0x0x7ff786dd0cab]\n\t(No symbol) [0x0x7ff786dc42c0]\n\t(No symbol) [0x0x7ff786dc4162]\n\t(No symbol) [0x0x7ff786d95d68]\n\t(No symbol) [0x0x7ff786d93d03]\n\t(No symbol) [0x0x7ff786e79011]\n\t(No symbol) [0x0x7ff786e3866a]\n\t(No symbol) [0x0x7ff786e60dbe]\n\t(No symbol) [0x0x7ff786e38443]\n\t(No symbol) [0x0x7ff786e01311]\n\t(No symbol) [0x0x7ff786e020a3]\n\tGetHandleVerifier [0x0x7ff7872de26d+2926461]\n\tGetHandleVerifier [0x0x7ff7872d8993+2903715]\n\tGetHandleVerifier [0x0x7ff7872f6aed+3026941]\n\tGetHandleVerifier [0x0x7ff7870416fe+187406]\n\tGetHandleVerifier [0x0x7ff7870496ef+220159]\n\tGetHandleVerifier [0x0x7ff78702faf4+114692]\n\tGetHandleVerifier [0x0x7ff78702fca9+115129]\n\tGetHandleVerifier [0x0x7ff7870164d8+10728]\n\tBaseThreadInitThunk [0x0x7ffe499c7374+20]\n\tRtlUserThreadStart [0x0x7ffe4a2fcc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_environment.py\", line 24, in login_to_environment\n    driver = create_driver(driver_path)\n  File \"D:\\PycharmProjects\\APS\\Utils\\driver_manager.py\", line 34, in create_driver\n    driver.maximize_window()  # 最大化浏览器窗口\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 622, in maximize_window\n    self.execute(command, None)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754046588957, "stop": 1754046590703}], "start": 1754046588957, "stop": 1754046591065}