{"uuid": "1800de04-88a1-47b9-b45d-4c063d6156f6", "children": ["762c30a0-8945-4791-83eb-36fca6f20d6d"], "befores": [{"name": "login_to_resourceAllocation", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff794406f65+78965]\n\tGetHandleVerifier [0x0x7ff794406fc0+79056]\n\t(No symbol) [0x0x7ff794199dda]\n\t(No symbol) [0x0x7ff7941720d1]\n\t(No symbol) [0x0x7ff79421ff4e]\n\t(No symbol) [0x0x7ff7942406cd]\n\t(No symbol) [0x0x7ff794218443]\n\t(No symbol) [0x0x7ff7941e1311]\n\t(No symbol) [0x0x7ff7941e20a3]\n\tGetHandleVerifier [0x0x7ff7946be26d+2926461]\n\tGetHandleVerifier [0x0x7ff7946b8993+2903715]\n\tGetHandleVerifier [0x0x7ff7946d6aed+3026941]\n\tGetHandleVerifier [0x0x7ff7944216fe+187406]\n\tGetHandleVerifier [0x0x7ff7944296ef+220159]\n\tGetHandleVerifier [0x0x7ff79440faf4+114692]\n\tGetHandleVerifier [0x0x7ff79440fca9+115129]\n\tGetHandleVerifier [0x0x7ff7943f64d8+10728]\n\tBaseThreadInitThunk [0x0x7fffd9ac7374+20]\n\tRtlUserThreadStart [0x0x7fffdad1cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_resourceAllocation.py\", line 53, in login_to_resourceAllocation\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 32, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 16, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1758106305070, "stop": 1758106307133}], "start": 1758106305070, "stop": 1758106307354}