{"uuid": "acf6ffca-02af-4663-9e33-c5c42760169b", "children": ["0011f227-3ee8-4c4c-aa8b-170ced1d271b"], "befores": [{"name": "login_to_environment", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff787026f65+78965]\n\tGetHandleVerifier [0x0x7ff787026fc0+79056]\n\t(No symbol) [0x0x7ff786db9dda]\n\t(No symbol) [0x0x7ff786d920d1]\n\t(No symbol) [0x0x7ff786e3ff4e]\n\t(No symbol) [0x0x7ff786e606cd]\n\t(No symbol) [0x0x7ff786e38443]\n\t(No symbol) [0x0x7ff786e01311]\n\t(No symbol) [0x0x7ff786e020a3]\n\tGetHandleVerifier [0x0x7ff7872de26d+2926461]\n\tGetHandleVerifier [0x0x7ff7872d8993+2903715]\n\tGetHandleVerifier [0x0x7ff7872f6aed+3026941]\n\tGetHandleVerifier [0x0x7ff7870416fe+187406]\n\tGetHandleVerifier [0x0x7ff7870496ef+220159]\n\tGetHandleVerifier [0x0x7ff78702faf4+114692]\n\tGetHandleVerifier [0x0x7ff78702fca9+115129]\n\tGetHandleVerifier [0x0x7ff7870164d8+10728]\n\tBaseThreadInitThunk [0x0x7ffe499c7374+20]\n\tRtlUserThreadStart [0x0x7ffe4a2fcc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_environment.py\", line 30, in login_to_environment\n    page.login(DateDriver().username, DateDriver().password, DateDriver().planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 30, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 14, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 70, in enter_text\n    element.send_keys(text)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 303, in send_keys\n    self._execute(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 572, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754045733159, "stop": 1754045739038}], "start": 1754045733159, "stop": 1754045739244}