{"uuid": "e600a23e-dadb-4473-8ae6-c5ca5d3268d1", "children": ["bc9e9591-2a50-4b1b-b82a-3f5ac81f7017"], "befores": [{"name": "login_to_role", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7bbc26f65+78965]\n\tGetHandleVerifier [0x0x7ff7bbc26fc0+79056]\n\t(No symbol) [0x0x7ff7bb9b9dda]\n\t(No symbol) [0x0x7ff7bb9a5bc5]\n\t(No symbol) [0x0x7ff7bb9cac04]\n\t(No symbol) [0x0x7ff7bba40195]\n\t(No symbol) [0x0x7ff7bba606cd]\n\t(No symbol) [0x0x7ff7bba38443]\n\t(No symbol) [0x0x7ff7bba01311]\n\t(No symbol) [0x0x7ff7bba020a3]\n\tGetHandleVerifier [0x0x7ff7bbede26d+2926461]\n\tGetHandleVerifier [0x0x7ff7bbed8993+2903715]\n\tGetHandleVerifier [0x0x7ff7bbef6aed+3026941]\n\tGetHandleVerifier [0x0x7ff7bbc416fe+187406]\n\tGetHandleVerifier [0x0x7ff7bbc496ef+220159]\n\tGetHandleVerifier [0x0x7ff7bbc2faf4+114692]\n\tGetHandleVerifier [0x0x7ff7bbc2fca9+115129]\n\tGetHandleVerifier [0x0x7ff7bbc164d8+10728]\n\tBaseThreadInitThunk [0x0x7ffae7f27374+20]\n\tRtlUserThreadStart [0x0x7ffae8d3cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_role.py\", line 49, in login_to_role\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 33, in login\n    self.enter_password(password)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 20, in enter_password\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入密码\"]', password)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 70, in enter_text\n    element.clear()  # 清空文本框\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 154, in clear\n    self._execute(Command.CLEAR_ELEMENT)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 572, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1757303662660, "stop": 1757303668812}], "start": 1757303662660, "stop": 1757303669000}