{"uuid": "4bb55cbc-4549-4cd7-9c3e-5565ee0da125", "children": ["ce1b8bf5-2b6e-4675-aa80-f42e61a46089"], "befores": [{"name": "login_to_userrole", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff6f4666f65+78965]\n\tGetHandleVerifier [0x0x7ff6f4666fc0+79056]\n\t(No symbol) [0x0x7ff6f43f9dda]\n\t(No symbol) [0x0x7ff6f43d20d1]\n\t(No symbol) [0x0x7ff6f447ff4e]\n\t(No symbol) [0x0x7ff6f44a06cd]\n\t(No symbol) [0x0x7ff6f4478443]\n\t(No symbol) [0x0x7ff6f4441311]\n\t(No symbol) [0x0x7ff6f44420a3]\n\tGetHandleVerifier [0x0x7ff6f491e26d+2926461]\n\tGetHandleVerifier [0x0x7ff6f4918993+2903715]\n\tGetHandleVerifier [0x0x7ff6f4936aed+3026941]\n\tGetHandleVerifier [0x0x7ff6f46816fe+187406]\n\tGetHandleVerifier [0x0x7ff6f46896ef+220159]\n\tGetHandleVerifier [0x0x7ff6f466faf4+114692]\n\tGetHandleVerifier [0x0x7ff6f466fca9+115129]\n\tGetHandleVerifier [0x0x7ff6f46564d8+10728]\n\tBaseThreadInitThunk [0x0x7ffae7f27374+20]\n\tRtlUserThreadStart [0x0x7ffae8d3cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_userRole.py\", line 48, in login_to_userrole\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 32, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 16, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1757503224078, "stop": 1757503225940}], "start": 1757503224078, "stop": 1757503226308}