{"uuid": "f7d82e3f-0e44-4e36-9875-c2a46e77d37d", "children": ["94c77fba-fec7-4dc0-8e0c-634aae26e106"], "befores": [{"name": "login_to_planUnit", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x0x7ff726176f65+78965]\n\tGetHandleVerifier [0x0x7ff726176fc0+79056]\n\t(No symbol) [0x0x7ff725f09dda]\n\t(No symbol) [0x0x7ff725f602ea]\n\t(No symbol) [0x0x7ff725f6059c]\n\t(No symbol) [0x0x7ff725fb3f37]\n\t(No symbol) [0x0x7ff725f886af]\n\t(No symbol) [0x0x7ff725fb0dbe]\n\t(No symbol) [0x0x7ff725f88443]\n\t(No symbol) [0x0x7ff725f51311]\n\t(No symbol) [0x0x7ff725f520a3]\n\tGetHandleVerifier [0x0x7ff72642e26d+2926461]\n\tGetHandleVerifier [0x0x7ff726428993+2903715]\n\tGetHandleVerifier [0x0x7ff726446aed+3026941]\n\tGetHandleVerifier [0x0x7ff7261916fe+187406]\n\tGetHandleVerifier [0x0x7ff7261996ef+220159]\n\tGetHandleVerifier [0x0x7ff72617faf4+114692]\n\tGetHandleVerifier [0x0x7ff72617fca9+115129]\n\tGetHandleVerifier [0x0x7ff7261664d8+10728]\n\tBaseThreadInitThunk [0x0x7ff9d9c27374+20]\n\tRtlUserThreadStart [0x0x7ff9db07cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_planUnit.py\", line 61, in login_to_planUnit\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 32, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 16, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 146, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1757073389098, "stop": 1757073404900}], "start": 1757073389098, "stop": 1757073405204}